# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from main.Decode_inf import Ui_DecodeWindow
from main.newqr import Ui_QR


class Ui_MainWindow(object):
    def openDecode_inf(self):
        self.Decode_inf = QtWidgets.QMainWindow()
        self.ui = Ui_DecodeWindow()
        self.ui.setupUi_decode(self.Decode_inf)
        self.Decode_inf.show()

    def open_new_qr(self):
        self.Code_to_picture = QtWidgets.QMainWindow()
        self.open_new_qr = Ui_QR()
        self.open_new_qr.setupUi_code(self.Code_to_picture)
        self.Code_to_picture.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 190, 231, 91))
        self.pushButton.setMinimumSize(QtCore.QSize(221, 91))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.openDecode_inf)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 60, 231, 91))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.open_new_qr)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR Creater"))
        self.pushButton.setText(_translate("MainWindow", "Декодировать картинку в текст"))
        self.pushButton_2.setText(_translate("MainWindow", "Закодировать текст в картинку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
