# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Decode_inf.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QPushButton, QLineEdit,
                             QInputDialog, QApplication, QFileDialog, QMainWindow, QTextEdit, QAction)
from PIL import Image
from read_create.main import get_text_from_image

class Ui_DecodeWindow(object):
    def setupUi_decode(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 682)
        MainWindow.setMinimumSize(QtCore.QSize(919, 682))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 170, 400, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Plain_text_Edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Plain_text_Edit.setGeometry(QtCore.QRect(440, 270, 461, 301))
        self.Plain_text_Edit.setObjectName("lineEdit_2")
        self.Plain_text_Edit.setReadOnly(True)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 175, 381, 381))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 381, 381))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.action.triggered.connect(self.openPicture)
        self.pushButton_2.clicked.connect(self.show_text)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Декодировать"))
        self.Plain_text_Edit.setPlaceholderText(_translate("MainWindow", "                         Место для декодированной информации"))
        self.label_3.setText(_translate("MainWindow", "                             Место для QR изображения"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "Загрузить картинку"))

    def openPicture(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        self.label_3.setPixmap(QtGui.QPixmap(path))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        img = Image.open(path)
        img.save("qr_picture.jpg")

    def show_text(self):
        text = get_text_from_image(Image.open("qr_picture.jpg"))
        print(text)
        self.Plain_text_Edit.appendPlainText(text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_DecodeWindow()
    ui.setupUi_decode(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
