# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QR.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QR(object):
    def setupUi(self, QR):
        QR.setObjectName("QR")
        QR.resize(800, 512)
        QR.setMinimumSize(QtCore.QSize(800, 512))
        QR.setMaximumSize(QtCore.QSize(800, 512))
        QR.setAccessibleName("")
        QR.setStyleSheet("selection-background-color: rgb(191, 63, 0);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(QR)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 80, 311, 381))
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(480, 80, 311, 381))
        self.listView_2.setStyleSheet("border-color: rgb(0, 0, 19)rgba(58, 0, 179, 139)")
        self.listView_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listView_2.setObjectName("listView_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 220, 141, 61))
        self.pushButton.setStyleSheet("background-color: rgb(176, 173, 177);\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(8, 20, 783, 50))
        self.lineEdit.setMinimumSize(QtCore.QSize(783, 50))
        self.lineEdit.setStatusTip("")
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32765)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        QR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        QR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QR)
        self.statusbar.setObjectName("statusbar")
        QR.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(QR)
        self.action.setObjectName("action")
        self.actionSave_as = QtWidgets.QAction(QR)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menufile.addAction(self.action)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionSave_as)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(QR)
        QtCore.QMetaObject.connectSlotsByName(QR)

    def retranslateUi(self, QR):
        _translate = QtCore.QCoreApplication.translate
        QR.setWindowTitle(_translate("QR", "QR creater"))
        self.pushButton.setText(_translate("QR", "Преобразовать в код"))
        self.lineEdit.setToolTip(_translate("QR", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit.setWhatsThis(_translate("QR", "<html><head/><body><p>Введите текст который нужно закодировать...</p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("QR", "Введите текст для кодирвоания"))
        self.menufile.setTitle(_translate("QR", "Файл"))
        self.action.setText(_translate("QR", "Загрузить картинку"))
        self.action.setIconText(_translate("QR", "Загрузить картинку"))
        self.actionSave_as.setText(_translate("QR", "Сохранить как"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QR = QtWidgets.QMainWindow()
    ui = Ui_QR()
    ui.setupUi(QR)
    QR.show()
    sys.exit(app.exec_())
